name: CML

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: iterative/setup-cml@v1
        with:
          sudo: false
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run DVC
        run: |
          dvc repro
      - name: Setup Git User
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Publish results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          CIREVISION=$(git rev-parse HEAD)
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git add .
          git commit -m "CML auto commit"
          git checkout -b "cml_${CIREVISION:0:10}"
          git push --set-upstream origin "cml_${CIREVISION:0:10}"
          git push
          gh pr create --fill --base $BRANCH
          
          gh pr merge --rebase "cml_${CIREVISION:0:10}"
          echo "## Report" >> report.md
          dvc metrics show --md >> report.md
          npx cml-send-comment report.md --commit-sha=$CIREVISION
